### ISSUE TITLE
Any updates?

### ISSUE THREAD

**Issue by chrissKLO** [AndyTWF/sector-file-compiler#37]
Hello! Is there any idea yet when this compiler will combine everything soon?
Looking to use it for a current project in France. I see it is missing AIRSPACE, FREETEXT, POSITIONS etc....

Appreciate your work!

Many Thanks!
Chriss

**Comment by AndyTWF** [comment]
Hi Chriss!

Been a bit of a busy month for me around Christmas, but hoping to get things rolling again in the new year! :)

**Comment by chrissKLO** [comment]
No worries, looking forward to this compiler being finished. While testing it yesterday I noticed that it doesn't seem to add VORs with two letter identifiers? Could that possibly be added in the validator code?

**Comment by AndyTWF** [comment]
Yes no problem, will do that :)

**Comment by AndyTWF** [comment]
@chrissKLO The latest version of master should allow 2 letter VORs :)

**Comment by chrissKLO** [comment]
@AndyTWF Just tested it this morning works like a charm! Thanks for your work on this wonderful tool!
